### ISSUE TITLE
Update package.json file to have proper platforms key 

### ISSUE THREAD

**Issue by NathanaelA** [shripalsoni04/nativescript-canvas-interface#1]
The package.json filed is missing the nativescript { platforms { ios: "version", android: "version" } } keys.

This means this plugin is not properly formed and might not be installable...

**Comment by shripalsoni04** [comment]
Actually, after reading package.json specification at http://docs.nativescript.org/plugins/plugins#packagejson-specification, I kept it blank as it is specified that it can be blank. 

I am able to install the plugin in my demo app without any issues on both Android/iOS. I tried with 1.5 and 1.6 runtimes.

Are you getting any issue while installing it?

**Comment by NathanaelA** [comment]
Actually there are two reasons to fix this.  
#1. By leaving it blank you are letting TNS believe it will work on the new Windows platform that is coming out shortly.
#2. The next reason is that I use those fields to determine the proper platform icons on the http://plugins.nativescript.rocks  -- No platforms = no icons.  :frowning:

**Comment by shripalsoni04** [comment]
Thanks for pointing out windows platform support issue. I have specified runtime version of android/ios in package.json.
